version: '2'
services:
  vault:
    image: "vault"
    hostname: "vault"
    container_name: "vault"
    environment:
      VAULT_ADDR: http://127.0.0.1:8200
    ports:
      - "8200:8200"
    volumes:
      - ./config:/config
      - ./policies:/policies
      - ./data:/vault
    entrypoint: /wait-for-it.sh -t 20 -h consul -p 8500 -s -- vault server -config=/config/with-consul.hcl

  vault-ui:
    image: "djenriquez/vault-ui"
    container_name: "vault-ui"
    ports:
      - "8000:8000"
    environment:
      VAULT_URL_DEFAULT: http://vault:8200
      VAULT_AUTH_DEFAULT: USERNAMEPASSWORD
    links:
      - vault
    depends_on:
      - vault